services:
  test_app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: test_fastapi_app
    ports:
      - "8001:8000"
    depends_on:
      test_postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - test-network

  test_postgres:
    image: postgres:latest
    container_name: test_postgres_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  test-network:
    driver: bridge